from enum import StrEnum

class StatusCode(StrEnum):
    OK = "OK"
    NO_RESULTS = "NO_RESULTS"
    SOURCE_NOT_CONFIGURED = "SOURCE_NOT_CONFIGURED"
    HTTP_ERROR = "HTTP_ERROR"
    TIMEOUT = "TIMEOUT"
    NETWORK_ERROR = "NETWORK_ERROR"
    INVALID_RESPONSE = "INVALID_RESPONSE"
    PARSER_ERROR = "PARSER_ERROR"
    MISSING_OFFICIAL_SOURCE = "MISSING_OFFICIAL_SOURCE"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    PARTIAL_DATA = "PARTIAL_DATA"
    VACANCY_NOT_FOUND = "VACANCY_NOT_FOUND"
    NO_ORGANS_SELECTED = "NO_ORGANS_SELECTED"
    BASELINE_CREATED = "BASELINE_CREATED"
    NO_NEW_ITEMS = "NO_NEW_ITEMS"
    TELEGRAM_NOT_CONFIGURED = "TELEGRAM_NOT_CONFIGURED"
    DRY_RUN = "DRY_RUN"
    PARTIAL_ERROR = "PARTIAL_ERROR"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"

VALID_STATUS_CODES = {code.value for code in StatusCode}
